require "bundler/gem_tasks"
require "rake/extensiontask"
require "rake/testtask"

# Configure the extension task
Rake::ExtensionTask.new("amoskeag_native") do |ext|
  ext.lib_dir = "lib"
  ext.ext_dir = "ext/amoskeag"
end

# Test task (if tests exist)
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

# Default task
task default: [:compile, :test]

# Clean task to remove built files
desc "Clean built files"
task :clean do
  sh "cd ext/amoskeag && make clean" if File.exist?("ext/amoskeag/Makefile")
  sh "cd ext/amoskeag && cargo clean" if File.exist?("ext/amoskeag/Cargo.toml")
  FileUtils.rm_rf("lib/amoskeag_native.bundle")
  FileUtils.rm_rf("lib/amoskeag_native.so")
  FileUtils.rm_rf("tmp")
end

# Build task
desc "Build the gem"
task build: :compile do
  sh "gem build amoskeag-rb.gemspec"
end

# Install task
desc "Build and install the gem locally"
task install: :build do
  sh "gem install amoskeag-rb-*.gem"
end
