require "bundler/gem_tasks"
require "rake/extensiontask"
require "rake/testtask"

# Configure the extension task
Rake::ExtensionTask.new("amoskeag_native") do |ext|
  ext.lib_dir = "lib"
  ext.ext_dir = "amoskeag"
  ext.source_pattern = "*.{c,h,rs}"
end

# Test tasks
namespace :test do
  desc "Run unit tests"
  Rake::TestTask.new(:unit) do |t|
    t.libs << "test"
    t.libs << "lib"
    t.test_files = FileList["test/unit/*_test.rb"]
    t.verbose = true
    t.warning = false
  end

  desc "Run integration tests"
  Rake::TestTask.new(:integration) do |t|
    t.libs << "test"
    t.libs << "lib"
    t.test_files = FileList["test/integration/*_test.rb"]
    t.verbose = true
    t.warning = false
  end

  desc "Run edge case tests"
  Rake::TestTask.new(:edge_cases) do |t|
    t.libs << "test"
    t.libs << "lib"
    t.test_files = FileList["test/edge_cases/*_test.rb"]
    t.verbose = true
    t.warning = false
  end

  desc "Run all tests"
  task all: [:unit, :integration, :edge_cases]
end

# Main test task runs all tests
desc "Run all tests"
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.verbose = true
  t.warning = false
end

# Default task
task default: [:compile, :test]

# Clean task to remove built files
desc "Clean built files"
task :clean do
  sh "cd ext/amoskeag && make clean" if File.exist?("ext/amoskeag/Makefile")
  sh "cd ext/amoskeag && cargo clean" if File.exist?("ext/amoskeag/Cargo.toml")
  FileUtils.rm_rf("lib/amoskeag_native.bundle")
  FileUtils.rm_rf("lib/amoskeag_native.so")
  FileUtils.rm_rf("tmp")
end

# Build task
desc "Build the gem"
task build: :compile do
  sh "gem build amoskeag-rb.gemspec"
end

# Install task
desc "Build and install the gem locally"
task install: :build do
  sh "gem install amoskeag-rb-*.gem"
end
